# Generated by Django 3.2.12 on 2022-03-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pochi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rgb_base64', models.TextField(blank=True, default='', null=True, verbose_name='画像データ')),
            ],
            options={
                'verbose_name': 'ぽちぽち',
                'verbose_name_plural': 'ぽちぽち',
                'db_table': 'pochi',
            },
        ),
    ]
